lab7/myimgur/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('sign-up', views.SignUpView.as_view(), name='signup'),
    path('<int:account_id>/', views.profile_page, name="profile_page")
]

lab7/myimgur/app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:image_id>/', views.detail, name='detail'),
    path('<int:image_id>/comment', views.comment, name='comment'),
<<<<<<< HEAD
    path('<int:image_id>/comment/<int:comment_id>/approve', views.approve_comment, name='approve_comment'),
    path('<int:image_id>/comment/<int:comment_id>/like', views.like_comment, name='like_comment'),
    path('<int:image_id>/upvote', views.upvote, name='upvote'),
    path('<int:image_id>/downvote', views.downvote, name='downvote'),
    path('new',views.create_image, name='create_image'),
    path('<int:image_id>/edit',views.update_image, name="edit_image"),
    path('<int:image_id>/delete',views.delete_image, name="delete_image"),
=======
>>>>>>> upstream/master
]

lab7/myimgur/imgur/urls.py
from django.contrib import admin
from django.urls import include,path
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
<<<<<<< HEAD
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
=======
>>>>>>> upstream/master
    path('images/', include('app.urls')),
    path('', views.index, name='index'), 
]

lab7/myimgur/app/templates/app/base.html
{% load static %}
<html>
  <head>
    <title>My Lame Imgur</title>


    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet"/>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>

    {% block extrahead %}
    {% endblock %}

    <link rel="stylesheet" href="{% static 'app/css/app.css' %}">
  </head>
  <body>
    <div class="page-header">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">My Lame Imgur</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
<<<<<<< HEAD
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="#">Hi {{ user.username }}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:profile_page' user.id %}">Profile page</a>
              </li>
              {% if user.is_superuser %}
                <li class="nav-item">
                  <a class="nav-link" href="/admin">Admin dasboard</a>
                </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
               {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:signup' %}">Sign up</a>
                </li>
              {% endif %}
          </ul>
=======
>>>>>>> upstream/master
        </div>
      </nav>

    </div>
    <div class="content container">
      <div class="row">
        <div class="col-md-12">
          <div class="jumbotron fluid-jumbotron">
            <div class="container">
              <h1 class="display-4">My Lame Imgur</h1>
              <p class="lead">Your one stop place for posting your lamest images!</p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

lab7/myimgur/app/templates/app/create_image.html
{% extends 'app/base.html' %}

{% block extrahead %}
{{ form.media }}
{% endblock extrahead %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
          {% if action == 'create' %}
          <h2 class="text-center">Submit new image</h2>
          {% else %}
          <h2 class="text-center">Edit image</h2>
          {% endif %}
            
        </div>
        
    </div>
      <form method="post">
        {% csrf_token %}
        {% include 'includes/bs4_form.html' with form=form %}
        <div class="col-md-8 mx-auto">
            <input type="submit" value="Submit" class="btn btn-primary text-centar">
        </div>
          
      </form>
  </div>
</div>
{% endblock %}

lab7/myimgur/app/templates/app/detail.html
{% extends 'app/base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
<<<<<<< HEAD
      <div>
        Posted by: <a href="{% url 'accounts:profile_page' image.user.id %}">{{ image.user.username }}</a>
      </div>
      <div class="date">
        {{ image.pub_date }}
      </div>
      {% include "includes/vote_buttons.html" with image=image vote=vote %}
=======
      <div class="date">
        {{ image.pub_date }}
      </div>
>>>>>>> upstream/master
      <h2>{{ image.title }}</h2>
      <img class="app-fit" src="{{image.url}}" alt=""/>
    </div>
    <div class="col-md-6">
      <h3>Description</h3>
      <p>{{ image.description|linebreaksbr }}</p>
      <h3>Comments</h3>
<<<<<<< HEAD
      {% for comment,like in comments_with_likes %}
        <div class="border comment">
          
          <p class="red">
            Author: <a href="{% url 'accounts:profile_page' image.user.id %}">{{ comment.user.username }}</a> ({{comment.created_at}}) Likes: {{comment.likes_count}}
          </p>
          {% if user.is_authenticated %}
          <form action="{% url 'app:like_comment' image.id comment.id %}" method="post" class="form-inline float-right">
            {% csrf_token %}
            <input type="submit" value="Like" class="btn border {{like|yesno:'btn-primary,'}}">
          </form>
          {% endif %}
          {% if comment.approved == False %}
          <form action="{% url 'app:approve_comment' image.id comment.id %}" method="post" class="form-inline float-right">
            {% csrf_token %}
            <input type="submit" value="approve comment" class="btn border">
          </form>
          {% endif %}
=======
      {% for comment in comments %}
        <div class="border comment">
          
          <p class="red">
            Author: {{ comment.author }} ({{comment.created_at}})
          </p>
>>>>>>> upstream/master
          <p class="secondary">
            {{ comment.text }}
          </p>
        </div>
      {% endfor %}
<<<<<<< HEAD
      {% if user.is_authenticated %}
=======

>>>>>>> upstream/master
      <h2>Post a comment</h2>
      {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

      <form action="{% url 'app:comment' image.id %}" method="post" class="border">
        {% csrf_token %}
<<<<<<< HEAD
        {% include "includes/bs4_form.html" with form=form %}

        <input type="submit" value="Post Comment" class="btn btn-lg btn-primary btn-block">
      </form>
      {% endif %}
      
=======
        <p>
          <label for="comment_author">Author </label><br>
          <input type="text" name="author" id="comment_author" value="">
        </p>
        <p>
          <label for="comment_text">Comment </label><br>
          <textarea  name="comment" id="comment_text" rows="4" cols="50">
          </textarea>
        </p>

        <input type="submit" value="Vote">
      </form>
>>>>>>> upstream/master
    </div>
  </div>
</div>
{% endblock %}

lab7/myimgur/app/templates/app/index.html
{% extends 'app/base.html' %}

{% block content %}
<<<<<<< HEAD
  <div class="row">
    <div class="col-md-10">
      {% if user.is_authenticated %}
      <p>
        <a href="{% url 'app:create_image' %}">Submit new image</a>
      </p>
      {% endif %}
    </div>
  </div>
    {% for image,vote in images_with_votes %}
      
=======
    {% for image in images %}
      <div class="container">
>>>>>>> upstream/master
        <div class="row">
          <div class="col-md-2">
            <img class="app-fit" src="{{image.url}}" alt=""/>
          </div>
          <div class="col-md-10">
            <div class="date">
              <p class="red">
<<<<<<< HEAD
              Posted by: <a href="{% url 'accounts:profile_page' image.user.id %}">{{ image.user.username }}</a> Published: {{ image.pub_date }}; 
              Comments: 
              {% if user.is_superuser %}
              {{image.admin_comments_count}}
              {% else %}
              {{image.user_comments_count}}
              {% endif %}

              {% if user.is_superuser or image.user == user %}
              <a href="{% url 'app:edit_image' image.id %}">Edit</a>
             {% include "includes/delete_image_link.html" with image=image %}
              {% endif %}
              </p>
            </div>
            {% include "includes/vote_buttons.html" with image=image vote=vote %}
=======
              Score: {{ image.votes }}; Published: {{ image.pub_date }};  Comments: {{ image.comment_set.count }} 
              </p>
            </div>
>>>>>>> upstream/master
            <h2><a href="{% url 'app:detail' image.id %}">{{ image.title }}</a></h2>
            <p>{{ image.description|linebreaksbr }}</p>
          </div>
        </div>
<<<<<<< HEAD
      
=======
      </div>
>>>>>>> upstream/master
    {% endfor %}
{% endblock %}

lab7/myimgur/app/templates/app/profile_page.html
{% extends 'app/base.html' %}
{% block content %}
<div class="row">
 <h1 class="m-auto">{{ selected_user.username }}'s Profile</h1>
</div>
<div class="row">
    <div class="col-md-6">
        <h2 class="m-auto">Posted images</h2>
        {% for image in images%}

        <div class="row">
          <div class="col-md-2">
            <img class="app-fit" src="{{image.url}}" alt=""/>
          </div>
          <div class="col-md-10">
            <div class="date">
              <p class="red">
              Published: {{ image.pub_date }};  Comments: {{ image.comment_set.count }}; Score: {{image.votes_score}}
              </p>
            </div>
            <h2><a href="{% url 'app:detail' image.id %}">{{ image.title }}</a></h2>
            <p>{{ image.description|linebreaksbr }}</p>
          </div>
        </div>
      
    {% endfor %}
    </div>
    <div class="col-md-6">
        <h2 class="m-auto">Posted comments</h2>
        {% for comment in comments %}
        <div class="border comment">
          
          <p class="red">
           ({{comment.created_at}}) Likes: {{comment.likes_count}} Comment on: <a href="{% url 'app:detail' comment.image.id %}">{{ comment.image.title }}</a> 
          </p>
          <p class="secondary">
            {{ comment.text }}
          </p>
        </div>
      {% endfor %}
    </div>
</div>
{% endblock %}